name: Tap CI

on:
  pull_request:
  push:
    branches: [main]

jobs:
  audit:
    runs-on: macos-latest
    steps:
      - name: Checkout tap
        uses: actions/checkout@v4

      - name: Set up Homebrew
        uses: Homebrew/actions/setup-homebrew@main

      - name: Run brew audit
        run: brew audit --strict --online ./Formula/livewalls.rb
